[[main]]
name = 'Home'
url = '/'
weight = 10

[[main]]
name = 'About'
url = '/about/'
weight = 20

[[main]]
name = 'Career'
url = '/career/'
weight = 30

[[main]]
name = 'Trenches'
url = '/categories/trenches/'
weight = 40

[[main]]
name = 'Microsoft365'
url = '/categories/microsoft-365/'
weight = 50
