baseURL = 'https://blog.janlwrobel.it/'
locale = 'en-us'
title = 'Jan Lukasz Wrobel'
theme = "PaperMod"

[pagination]
pagerSize = 5

[params]
defaultTheme = "dark"
ShowReadingTime = true
ShowShareButtons = true
ShowPostNavLinks = true
ShowBreadCrumbs = true
ShowCodeCopyButtons = true
ShowWordCount = true
description = 'Real IT from the trenches'
disableSpecial1stPost = true

defaultContentLanguage = 'en'
defaultContentLanguageInSubdir = false

[taxonomies]
category = 'categories'
tag = 'tags'

[languages]

[languages.en]
label = '🇬🇧 English'
locale = 'en-gb'
weight = 1

[languages.pl]
label = '🇵🇱 Polski'
locale = 'pl-pl'
weight = 2

